"""empty message

Revision ID: efb39e6041ad
Revises: 6776bbf6044c
Create Date: 2023-07-20 13:56:29.806370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb39e6041ad'
down_revision = '6776bbf6044c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_user_id_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_user_id_fkey', 'admins', 'rooms', ['user_id'], ['id'])
    # ### end Alembic commands ###
